In [31]:
import pandas as pd
import numpy as np

# Read the dataset into csv file
# The file should contains all the features and intensities
# python counts index from 0
df = pd.read_csv("path/to/your/file.csv", header=[0], keep_default_na=False, na_values=[''])
df

,pixel_id,X,Y,393.2979,413.2663,256.264,301.1411,258.2794,149.0238,556.277,...,575.2675,1047.8058,691.4282,735.454,277.1408,237.078,426.3555,584.2993,Unnamed_1,Unnamed_2
0,899,8.10,-4.8,114251.0,57065.0,26146.0,51227.0,36034.0,21045.0,19530.0,...,266.0,32.0,267.0,129.0,1159.0,1155.0,46.0,127.0,1.0,899.0
1,900,8.15,-4.8,113206.0,43303.0,39977.0,42663.0,38918.0,28668.0,26110.0,...,228.0,3.0,72.0,22.0,924.0,1069.0,73.0,112.0,1.0,900.0
2,901,8.20,-4.8,96778.0,32367.0,54458.0,29755.0,40464.0,36761.0,33405.0,...,140.0,40.0,157.0,46.0,800.0,870.0,134.0,49.0,1.0,901.0
3,902,8.25,-4.8,102062.0,38044.0,48447.0,33709.0,39475.0,34720.0,31146.0,...,151.0,16.0,184.0,26.0,952.0,930.0,27.0,20.0,1.0,902.0
4,903,8.30,-4.8,104651.0,40890.0,42482.0,38694.0,39362.0,30599.0,26556.0,...,135.0,15.0,48.0,13.0,1165.0,1196.0,38.0,93.0,1.0,903.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16370,44789,14.40,-2.7,38362.0,5699.0,81191.0,5657.0,32642.0,41156.0,34395.0,...,310.0,33.0,62.0,91.0,401.0,600.0,78.0,184.0,1.0,44789.0
16371,44790,14.45,-2.7,40218.0,7384.0,76087.0,6470.0,30982.0,38750.0,35095.0,...,275.0,0.0,61.0,35.0,339.0,875.0,0.0,70.0,1.0,44790.0
16372,44791,14.50,-2.7,43742.0,7748.0,68029.0,6779.0,27575.0,37937.0,36002.0,...,183.0,0.0,90.0,81.0,874.0,770.0,230.0,100.0,1.0,44791.0
16373,44792,14.55,-2.7,45899.0,8570.0,75633.0,7115.0,31623.0,41617.0,34737.0,...,294.0,69.0,0.0,109.0,512.0,610.0,85.0,63.0,1.0,44792.0
16374,44793,14.60,-2.7,56691.0,10425.0,67390.0,10602.0,29210.0,38686.0,33249.0,...,210.0,56.0,47.0,61.0,389.0,975.0,176.0,150.0,1.0,44793.0

In [32]:
# adjust the number of columns based on the csv data file
# separate the pixel_id and coordinates from features(means m/z)
coor_columns = df.iloc[:, :3]
coor_columns

       pixel_id      X    Y
0           899   8.10 -4.8
1           900   8.15 -4.8
2           901   8.20 -4.8
3           902   8.25 -4.8
4           903   8.30 -4.8
...         ...    ...  ...
16370     44789  14.40 -2.7
16371     44790  14.45 -2.7
16372     44791  14.50 -2.7
16373     44792  14.55 -2.7
16374     44793  14.60 -2.7

[16375 rows x 3 columns]

In [33]:
# adjust the number of columns based on the csv data file
# separate the pixel_id and coordinates from features(means m/z)
peak_columns = df.iloc[:, 3:1003]
peak_columns

,393.2979,413.2663,256.264,301.1411,258.2794,149.0238,556.277,284.2952,394.3009,806.5699,...,1161.3395,750.4645,575.2675,1047.8058,691.4282,735.454,277.1408,237.078,426.3555,584.2993
0,114251.0,57065.0,26146.0,51227.0,36034.0,21045.0,19530.0,14946.0,27083.0,0.0,...,0.0,36.0,266.0,32.0,267.0,129.0,1159.0,1155.0,46.0,127.0
1,113206.0,43303.0,39977.0,42663.0,38918.0,28668.0,26110.0,19644.0,25244.0,24.0,...,0.0,23.0,228.0,3.0,72.0,22.0,924.0,1069.0,73.0,112.0
2,96778.0,32367.0,54458.0,29755.0,40464.0,36761.0,33405.0,28600.0,22831.0,18.0,...,29.0,32.0,140.0,40.0,157.0,46.0,800.0,870.0,134.0,49.0
3,102062.0,38044.0,48447.0,33709.0,39475.0,34720.0,31146.0,25124.0,22990.0,26.0,...,36.0,94.0,151.0,16.0,184.0,26.0,952.0,930.0,27.0,20.0
4,104651.0,40890.0,42482.0,38694.0,39362.0,30599.0,26556.0,22047.0,24427.0,0.0,...,0.0,66.0,135.0,15.0,48.0,13.0,1165.0,1196.0,38.0,93.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16370,38362.0,5699.0,81191.0,5657.0,32642.0,41156.0,34395.0,42588.0,8969.0,58.0,...,8.0,43.0,310.0,33.0,62.0,91.0,401.0,600.0,78.0,184.0
16371,40218.0,7384.0,76087.0,6470.0,30982.0,38750.0,35095.0,41539.0,8625.0,100.0,...,0.0,18.0,275.0,0.0,61.0,35.0,339.0,875.0,0.0,70.0
16372,43742.0,7748.0,68029.0,6779.0,27575.0,37937.0,36002.0,37093.0,11620.0,110.0,...,0.0,25.0,183.0,0.0,90.0,81.0,874.0,770.0,230.0,100.0
16373,45899.0,8570.0,75633.0,7115.0,31623.0,41617.0,34737.0,39756.0,10219.0,123.0,...,18.0,14.0,294.0,69.0,0.0,109.0,512.0,610.0,85.0,63.0
16374,56691.0,10425.0,67390.0,10602.0,29210.0,38686.0,33249.0,35530.0,12366.0,82.0,...,0.0,60.0,210.0,56.0,47.0,61.0,389.0,975.0,176.0,150.0

In [34]:
# Each pixel contains a full mass spectra.
# Total Ion Current (TIC) normalization: normalize each peak (m/z) in each pixel based on the TIC of that pixel.
# Total Ion Current (TIC) of a pixel = row sum of all feature columns
# drop the rows that are only zeros
row_sums = peak_columns.sum(axis=1)
zero_rows = row_sums[row_sums == 0].index
peak_columns = peak_columns.drop(zero_rows)
# each inetnstiy times 10e5 to make it a larger number, easier to read, wont' change the comparison
TIC_norm = 10e5*peak_columns.div(peak_columns.sum(axis=1), axis=0)
TIC_norm

,393.2979,413.2663,256.264,301.1411,258.2794,149.0238,556.277,284.2952,394.3009,806.5699,...,1161.3395,750.4645,575.2675,1047.8058,691.4282,735.454,277.1408,237.078,426.3555,584.2993
0,109196.720591,54540.536717,24989.343258,48960.800393,34439.914134,20114.003246,18666.024395,14284.813139,25884.891894,0.000000,...,0.000000,34.407418,254.232590,30.584372,255.188352,123.293249,1107.727715,1103.904669,43.965034,121.381725
1,108946.098599,41673.523555,38472.679749,41057.606527,37453.529541,27589.233385,25127.490013,18904.803287,24294.077284,23.096889,...,0.000000,22.134518,219.420441,2.887111,69.290666,21.172148,889.230210,1028.773911,70.253036,107.785480
2,92714.774986,31008.071276,52171.580485,28505.736115,38765.118674,35217.589155,32002.490839,27399.228798,21872.440304,17.244270,...,27.782435,30.656480,134.122099,38.320600,150.408354,44.068690,766.411994,833.473044,128.374009,46.942735
3,98310.377677,36645.568462,46666.172203,32469.915553,38023.967381,33443.752944,30001.126993,24200.485281,22144.927425,25.044285,...,34.676702,90.544723,145.449502,15.411868,177.236479,25.044285,917.006129,895.814811,26.007527,19.264835
4,101992.961432,39851.431835,41402.996508,37711.208203,38362.241621,29821.813713,25881.502172,21487.026600,23806.576802,0.000000,...,0.000000,64.323661,131.571125,14.619014,46.780844,12.669812,1135.410078,1165.622707,37.034835,90.637886
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16370,47191.826743,7010.745545,99878.828139,6959.078356,40155.247603,50628.925015,42311.737678,52390.530142,11033.405298,71.349928,...,9.841369,52.897361,381.353065,40.595649,76.270613,111.945577,493.298643,738.102707,95.953352,226.351497
16371,50535.473973,9278.281859,95606.261081,8129.805475,38930.082416,48690.875142,44098.226144,52195.361613,10837.646402,125.653871,...,0.000000,22.617697,345.548146,0.000000,76.648862,43.978855,425.966624,1099.471374,0.000000,87.957710
16372,55306.822507,9796.471601,86014.993103,8571.280458,34865.475530,47967.055129,45520.466003,46899.912378,14692.178628,139.082586,...,0.000000,31.609679,231.382848,0.000000,113.794843,102.415359,1105.074365,973.578102,290.809043,126.438715
16373,56758.838929,10597.687305,93527.991126,8798.430009,39105.095175,51463.705085,42955.876770,49162.386990,12636.845574,152.102163,...,22.258853,17.312441,363.561268,85.325604,0.000000,134.789722,633.140712,754.327801,105.111251,77.905986
16374,70579.403229,12978.961011,83899.489930,13199.323227,36365.990516,48163.461455,41394.481981,44234.291100,15395.475478,102.088710,...,0.000000,74.699056,261.446697,69.719119,58.514261,75.944040,484.298881,1213.859663,219.117231,186.747640

In [35]:
# drop zero rows if exists
coor_columns = coor_columns.drop(zero_rows)
coor_columns

       pixel_id      X    Y
0           899   8.10 -4.8
1           900   8.15 -4.8
2           901   8.20 -4.8
3           902   8.25 -4.8
4           903   8.30 -4.8
...         ...    ...  ...
16370     44789  14.40 -2.7
16371     44790  14.45 -2.7
16372     44791  14.50 -2.7
16373     44792  14.55 -2.7
16374     44793  14.60 -2.7

[16375 rows x 3 columns]

In [36]:
# put the pixel_id and coordinates back with TIC results as a new dataframe
# save the results
TIC_result = pd.concat([coor_columns, TIC_norm], axis=1)
TIC_result.to_csv("path/to/your/output/folder/result.csv", index=None)
TIC_result

,pixel_id,X,Y,393.2979,413.2663,256.264,301.1411,258.2794,149.0238,556.277,...,1161.3395,750.4645,575.2675,1047.8058,691.4282,735.454,277.1408,237.078,426.3555,584.2993
0,899,8.10,-4.8,109196.720591,54540.536717,24989.343258,48960.800393,34439.914134,20114.003246,18666.024395,...,0.000000,34.407418,254.232590,30.584372,255.188352,123.293249,1107.727715,1103.904669,43.965034,121.381725
1,900,8.15,-4.8,108946.098599,41673.523555,38472.679749,41057.606527,37453.529541,27589.233385,25127.490013,...,0.000000,22.134518,219.420441,2.887111,69.290666,21.172148,889.230210,1028.773911,70.253036,107.785480
2,901,8.20,-4.8,92714.774986,31008.071276,52171.580485,28505.736115,38765.118674,35217.589155,32002.490839,...,27.782435,30.656480,134.122099,38.320600,150.408354,44.068690,766.411994,833.473044,128.374009,46.942735
3,902,8.25,-4.8,98310.377677,36645.568462,46666.172203,32469.915553,38023.967381,33443.752944,30001.126993,...,34.676702,90.544723,145.449502,15.411868,177.236479,25.044285,917.006129,895.814811,26.007527,19.264835
4,903,8.30,-4.8,101992.961432,39851.431835,41402.996508,37711.208203,38362.241621,29821.813713,25881.502172,...,0.000000,64.323661,131.571125,14.619014,46.780844,12.669812,1135.410078,1165.622707,37.034835,90.637886
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16370,44789,14.40,-2.7,47191.826743,7010.745545,99878.828139,6959.078356,40155.247603,50628.925015,42311.737678,...,9.841369,52.897361,381.353065,40.595649,76.270613,111.945577,493.298643,738.102707,95.953352,226.351497
16371,44790,14.45,-2.7,50535.473973,9278.281859,95606.261081,8129.805475,38930.082416,48690.875142,44098.226144,...,0.000000,22.617697,345.548146,0.000000,76.648862,43.978855,425.966624,1099.471374,0.000000,87.957710
16372,44791,14.50,-2.7,55306.822507,9796.471601,86014.993103,8571.280458,34865.475530,47967.055129,45520.466003,...,0.000000,31.609679,231.382848,0.000000,113.794843,102.415359,1105.074365,973.578102,290.809043,126.438715
16373,44792,14.55,-2.7,56758.838929,10597.687305,93527.991126,8798.430009,39105.095175,51463.705085,42955.876770,...,22.258853,17.312441,363.561268,85.325604,0.000000,134.789722,633.140712,754.327801,105.111251,77.905986
16374,44793,14.60,-2.7,70579.403229,12978.961011,83899.489930,13199.323227,36365.990516,48163.461455,41394.481981,...,0.000000,74.699056,261.446697,69.719119,58.514261,75.944040,484.298881,1213.859663,219.117231,186.747640